// src/mockStudentData.js
// In a real application, this data would come from a database or API.
export const students = [
    { id: 1, rollNo: '10A-01', name: 'Aarav Sharma', class: '10', section: 'A' },
    { id: 2, rollNo: '10B-01', name: 'Vivaan Singh', class: '10', section: 'B' },
    { id: 3, rollNo: '9A-01', name: 'Aditya Kumar', class: '9', section: 'A' },
    { id: 4, rollNo: '10A-02', name: 'Vihaan Gupta', class: '10', section: 'A' },
    { id: 5, rollNo: '9B-01', name: 'Arjun Yadav', class: '9', section: 'B' },
    { id: 6, rollNo: '10C-01', name: 'Sai Patel', class: '10', section: 'C' },
    { id: 7, rollNo: '10A-03', name: 'Reyansh Reddy', class: '10', section: 'A' },
    { id: 8, rollNo: '9A-02', name: 'Krishna Verma', class: '9', section: 'A' },
    { id: 9, rollNo: '10B-02', name: 'Ishaan Jain', class: '10', section: 'B' },
    { id: 10, rollNo: '9C-01', name: 'Advik Mishra', class: '9', section: 'C' },
    { id: 11, rollNo: '10A-04', name: 'Ayaan Khan', class: '10', section: 'A' },
    { id: 12, rollNo: '10C-02', name: 'Dhruv Mehra', class: '10', section: 'C' },
    { id: 13, rollNo: '9B-02', name: 'Kabir Chopra', class: '9', section: 'B' },
    { id: 14, rollNo: '10A-05', name: 'Ansh Tiwari', class: '10', section: 'A' },
    { id: 15, rollNo: '9A-03', name: 'Kian Agarwal', class: '9', section: 'A' },
    { id: 16, rollNo: '10B-03', name: 'Rudra Shah', class: '10', section: 'B' },
    { id: 17, rollNo: '10A-06', name: 'Diya Mehta', class: '10', section: 'A' },
    { id: 18, rollNo: '9B-03', name: 'Saanvi Iyer', class: '9', section: 'B' },
    { id: 19, rollNo: '10C-03', name: 'Aanya Singhania', class: '10', section: 'C' },
    { id: 20, rollNo: '10A-07', name: 'Myra Joshi', class: '10', section: 'A' },
    { id: 21, rollNo: '9A-04', name: 'Pari Nair', class: '9', section: 'A' },
    { id: 22, rollNo: '10B-04', name: 'Kiara Bhat', class: '10', section: 'B' },
    { id: 23, rollNo: '9C-02', name: 'Anika Reddy', class: '9', section: 'C' },
    { id: 24, rollNo: '10A-08', name: 'Zara Kumar', class: '10', section: 'A' },
    { id: 25, rollNo: '10B-05', name: 'Amaira Gupta', class: '10', section: 'B' },
    { id: 26, rollNo: '9A-05', name: 'Ishita Verma', class: '9', section: 'A' },
    { id: 27, rollNo: '10A-09', name: 'Riya Patel', class: '10', section: 'A' },
    { id: 28, rollNo: '10C-04', name: 'Siya Singh', class: '10', section: 'C' },
    { id: 29, rollNo: '9B-04', name: 'Avni Jain', class: '9', section: 'B' },
    { id: 30, rollNo: '10A-10', name: 'Anaya Sharma', class: '10', section: 'A' },
];